-- Phase 11 — a short "what this class has covered so far" summary. Generated by the class-intake tool
-- (Opus, from a free-text class description) at setup, editable after, and fed to planning so the AI
-- builds on prior learning instead of re-teaching it. Cohort-level prose only; never an individual pupil.
ALTER TABLE group_courses ADD COLUMN covered_summary TEXT;
